sailboat_training: #namespace

    nsteps: 150

    sail_upper_limit: 90
    sail_lower_limit: -90
    rudder_upper_limit: 30
    rudder_lower_limit: -30

    goal_epsilon: 5
    max_distance_from_goal: 220.0 # Maximum distance regitered in observations, has to be bigger than the largest distance of the workspace.
    
    number_decimals_precision_obs: 1

    done_reward: 100.0
    vmg_reward_multiplier: 1
    dist_reward_multiplier: 5
    joint_movement_penalty: 0
    time_penalty: 3
    stall_kill: False

    running_step: 4.0 # Time for each step